services:
  capcut-mate-data:
    image: gogoshine/capcut-mate-data:latest
    #image: gogoshine/capcut-mate-data:sha-190a61f
    ports:
      - "30000:30000"
    volumes:
      - /opt/1panel/apps/openresty/openresty/www/sites/capcut-mate-data.jcaigc.cn/index/output:/app/output  # 挂载配置文件目录
      - /etc/localtime:/etc/localtime:ro  # 挂载主机时区
      - /etc/timezone:/etc/timezone:ro    # 挂载时区名称（可选）
    environment:
      # 草稿下载URL
      - DRAFT_URL=https://capcut-mate-data.jcaigc.cn/openapi/v1/get_draft
      # 用于将容器内部的文件路径转成URL，本质是将/app/替换成DOWNLOAD_URL得到下载路径
      - DOWNLOAD_URL=https://capcut-mate-data.jcaigc.cn/
      # 草稿提示URL
      - TIP_URL=
    mem_limit: 2G     # 内存限制
    memswap_limit: 2G # 总内存（物理内存 + Swap）限制
    cpus: '2'       # CPU使用率限制为150%，即容器最多可以使用1.5个完整的CPU核心
    oom_score_adj: -500  # 调整 OOM 杀手优先级
    restart: unless-stopped  # 除非手动停止，否则总是重启容器
    container_name: capcut-mate-data # 这里指容器名称，非必需，不指定时，名称为：<项目名称>-<服务名称>-<序号>
    #entrypoint: ["/bin/sh", "-c", "sleep 10000"]